#!/usr/bin/env bash
# Build the cortex_ring Rust staticlib for every Apple target, regenerate the cbindgen C header,
# and assemble Packages/CortexRing/CortexRingFFI.xcframework — the binary the SwiftPM
# `.binaryTarget` links (D-R1 / RESEARCH §3-A). This is the Phase-3 `make bootstrap` analogue:
# the xcframework is gitignored, so a fresh clone and CI must run this BEFORE `swift package
# resolve` / `xcodegen` (the FOUND-04 clean-clone caveat made explicit, not a silent break).
#
# Why an xcframework + .binaryTarget (not -L/-l .unsafeFlags): SwiftPM AND xcodebuild both link an
# xcframework natively, so this survives the dual build (`swift build` + `xcodebuild -scheme`).
# .unsafeFlags link paths break across the two working dirs (RESEARCH §3-A / Pitfall #6) — there
# are deliberately ZERO -L/-l flags anywhere in this script.
set -euo pipefail

# --- locate repo root (script lives in Tools/scripts/) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

RUST_DIR="Packages/CortexRing/rust"
MANIFEST="$RUST_DIR/Cargo.toml"
HEADER="$RUST_DIR/include/cortex_ring.h"
XCFRAMEWORK="Packages/CortexRing/CortexRingFFI.xcframework"
STAGE="$RUST_DIR/target/xcframework-stage"

# --- 1. toolchain presence (RESEARCH §3 clean-clone caveat / Pitfall #1) ---
if ! command -v cargo >/dev/null 2>&1; then
  cat >&2 <<'BOOTSTRAP'
ERROR: `cargo` not found. cortex_ring needs the Rust toolchain + cbindgen.
Bootstrap (the documented Phase-3 `make bootstrap` step, FOUND-04 analogue):
  brew install rustup-init && rustup-init -y --no-modify-path
  source "$HOME/.cargo/env"   # or: brew install rustup && rustup default stable
  rustup target add aarch64-apple-darwin x86_64-apple-darwin aarch64-apple-ios aarch64-apple-ios-sim
  brew install cbindgen       # or: cargo install cbindgen
Then re-run Tools/scripts/build-rust.sh.
BOOTSTRAP
  exit 1
fi
echo "cargo:    $(cargo --version)"
command -v cbindgen >/dev/null 2>&1 && echo "cbindgen: $(cbindgen --version)" || \
  echo "cbindgen: (not on PATH; build.rs uses the [build-dependencies] cbindgen to regenerate the header)"

# --- 2. cargo build --release per Apple target ---
# macOS device (arm64) + macOS host (x86_64, so the xcframework's macOS slice links on an Intel
# CI runner too) + the two iOS targets. iOS device/sim are separate xcframework slices.
MAC_TARGETS=(aarch64-apple-darwin x86_64-apple-darwin)
IOS_DEVICE_TARGET="aarch64-apple-ios"
IOS_SIM_TARGET="aarch64-apple-ios-sim"
ALL_TARGETS=("${MAC_TARGETS[@]}" "$IOS_DEVICE_TARGET" "$IOS_SIM_TARGET")

for T in "${ALL_TARGETS[@]}"; do
  echo "=== cargo build --release --target $T ==="
  cargo build --release --manifest-path "$MANIFEST" --target "$T"
done

# --- 3. confirm the vendored header was (re)generated by build.rs ---
test -f "$HEADER" || { echo "ERROR: $HEADER not generated by build.rs" >&2; exit 1; }

# --- 4. assemble the xcframework staging dirs (fat macOS lib + per-slice Headers w/ modulemap) ---
rm -rf "$STAGE"
mkdir -p "$STAGE/macos" "$STAGE/ios-device" "$STAGE/ios-sim" "$STAGE/headers"

# 4a. lipo the two macOS arches into one fat static lib (one macOS slice covers arm64 + x86_64).
MAC_FAT="$STAGE/macos/libcortex_ring.a"
lipo -create \
  "$RUST_DIR/target/aarch64-apple-darwin/release/libcortex_ring.a" \
  "$RUST_DIR/target/x86_64-apple-darwin/release/libcortex_ring.a" \
  -output "$MAC_FAT"
echo "lipo macOS fat lib: $(lipo -archs "$MAC_FAT")"

# 4b. iOS device + iOS simulator slices (single-arch each, arm64).
cp "$RUST_DIR/target/$IOS_DEVICE_TARGET/release/libcortex_ring.a" "$STAGE/ios-device/libcortex_ring.a"
cp "$RUST_DIR/target/$IOS_SIM_TARGET/release/libcortex_ring.a"    "$STAGE/ios-sim/libcortex_ring.a"

# 4c. shared headers dir: the committed cbindgen header + a Clang modulemap so Swift can
#     `import CortexRingFFI`. xcodebuild -create-xcframework copies this into every slice's Headers/.
cp "$HEADER" "$STAGE/headers/cortex_ring.h"
cat > "$STAGE/headers/module.modulemap" <<'MODMAP'
module CortexRingFFI {
    header "cortex_ring.h"
    export *
}
MODMAP

# --- 5. create the xcframework (refuses to overwrite → remove any stale output first) ---
rm -rf "$XCFRAMEWORK"
xcodebuild -create-xcframework \
  -library "$MAC_FAT"                       -headers "$STAGE/headers" \
  -library "$STAGE/ios-device/libcortex_ring.a" -headers "$STAGE/headers" \
  -library "$STAGE/ios-sim/libcortex_ring.a"    -headers "$STAGE/headers" \
  -output "$XCFRAMEWORK"

echo "OK: assembled $XCFRAMEWORK"
echo "    slices: $(/usr/bin/find "$XCFRAMEWORK" -maxdepth 1 -type d -name '*-*' -exec basename {} \; | paste -sd' ' -)"
