// REFIT-01 / D-15 — structural invariants on the committed steady-state constants.
//
// `KalmanConstants.swift` is GENERATED by `Decoder/scripts/fit_kalman_gain.py`. These tests need
// NO Wave-2 filter — they guard the code-gen invariants so a regeneration (or a hand-edit that
// CONTEXT forbids) cannot silently break the load-bearing structure: the gain's position rows must
// stay zero (the observability resolution, 07-RESEARCH §2.3), H must select velocity only, and A
// must carry the constant-acceleration `dt` coupling. A code-gen regression that breaks any of
// these fails CI (threat T-07-01-02).
import Testing

@testable import CortexReFIT

// The CortexReFIT library target sets `.defaultIsolation(MainActor.self)`, so its statics are
// MainActor-isolated; the suite adopts the same isolation to read them synchronously.
@Suite("REFIT-01: committed Kalman constants — structural invariants")
@MainActor
struct KalmanConstantsTests {
  /// The gain K has exactly zero position rows (rows 0, 1 = px, py) — position is unobservable from
  /// a velocity measurement, so it receives no correction (07-RESEARCH §2.3, threat T-07-01-02).
  @Test("K position rows (0,1) are exactly zero")
  func gainPositionRowsAreZero() {
    #expect(KalmanConstants.K.count == 6)
    #expect(KalmanConstants.K[0] == SIMD2<Float>(0, 0))
    #expect(KalmanConstants.K[1] == SIMD2<Float>(0, 0))
  }

  /// The velocity/acceleration rows of K are NOT all zero — the committed gain is real (a degenerate
  /// all-zero gain would also satisfy the position-row check, so guard against it).
  @Test("K velocity/acceleration rows (2..5) are non-zero")
  func gainVelocityRowsAreNonZero() {
    let velAccelRows = Array(KalmanConstants.K[2 ..< 6])
    let allZero = velAccelRows.allSatisfy { $0 == SIMD2<Float>(0, 0) }
    #expect(!allZero)
  }

  /// H = [0 I 0]: it selects (vx, vy) — columns 2, 3 — and nothing else. The 6-wide rows are stored
  /// as SIMD8 with 2 zero-pad lanes (Swift has no SIMD6), so columns 6, 7 are also zero.
  @Test("H equals [0 I 0] (velocity-selecting rows)")
  func measurementSelectsVelocity() {
    #expect(KalmanConstants.H.count == 2)
    // Row 0 selects vx (column 2).
    #expect(KalmanConstants.H[0] == SIMD8<Float>(0, 0, 1, 0, 0, 0, 0, 0))
    // Row 1 selects vy (column 3).
    #expect(KalmanConstants.H[1] == SIMD8<Float>(0, 0, 0, 1, 0, 0, 0, 0))
  }

  /// A is constant-acceleration: the position rows carry `dt` velocity coupling (columns 2, 3) and
  /// `½dt²` acceleration coupling (columns 4, 5); the diagonal is identity. Spot-check the cells.
  @Test("A carries dt velocity coupling and ½dt² acceleration coupling")
  func transitionHasConstantAccelerationStructure() {
    #expect(KalmanConstants.A.count == 6)
    let dt = KalmanConstants.dt
    #expect(dt == 0.02)
    let halfDtSq = 0.5 * dt * dt

    // Row 0 (px): [1, 0, dt, 0, ½dt², 0, 0, 0].
    #expect(KalmanConstants.A[0] == SIMD8<Float>(1, 0, dt, 0, halfDtSq, 0, 0, 0))
    // Row 1 (py): [0, 1, 0, dt, 0, ½dt², 0, 0].
    #expect(KalmanConstants.A[1] == SIMD8<Float>(0, 1, 0, dt, 0, halfDtSq, 0, 0))
    // Row 2 (vx): [0, 0, 1, 0, dt, 0, 0, 0].
    #expect(KalmanConstants.A[2] == SIMD8<Float>(0, 0, 1, 0, dt, 0, 0, 0))
    // Row 3 (vy): [0, 0, 0, 1, 0, dt, 0, 0].
    #expect(KalmanConstants.A[3] == SIMD8<Float>(0, 0, 0, 1, 0, dt, 0, 0))
    // Rows 4,5 (ax,ay): identity rows (acceleration persists).
    #expect(KalmanConstants.A[4] == SIMD8<Float>(0, 0, 0, 0, 1, 0, 0, 0))
    #expect(KalmanConstants.A[5] == SIMD8<Float>(0, 0, 0, 0, 0, 1, 0, 0))
  }

  /// Q (observable block) and R are square and carry the documented provenance dimensions.
  @Test("Qobs is 4x4 and R is 2x2 (provenance shapes)")
  func noiseProvenanceShapes() {
    #expect(KalmanConstants.Qobs.count == 4)
    #expect(KalmanConstants.R.count == 2)
    // R is diagonal (the default decoder-noise floor): off-diagonals zero, diagonal positive.
    #expect(KalmanConstants.R[0].y == 0)
    #expect(KalmanConstants.R[1].x == 0)
    #expect(KalmanConstants.R[0].x > 0)
    #expect(KalmanConstants.R[1].y > 0)
  }

  /// The package namespace metadata matches the 6-DOF / 2-measurement contract.
  @Test("CortexReFIT namespace dimensions match the 6-DOF / 2-measurement contract")
  func namespaceDimensions() {
    #expect(CortexReFIT.phase == 7)
    #expect(CortexReFIT.stateDimension == 6)
    #expect(CortexReFIT.measurementDimension == 2)
  }
}
