// RoundTripLog — Phase 8 (SYS-03/04, SC#2): the instrumented round-trip log that satisfies SC#2's
// acceptance bar "an instrumented log shows the round trip" (CONTEXT D-05, RESEARCH §0.2).
//
// Every closed-loop cycle (a Scan-Info OUTPUT report in -> an Item-Selection/Pointer intent out) appends
// exactly one timestamped `RoundTripEntry` here. The log is the regenerate-from-code provenance for the
// closed-loop claim — it is GENERATED by `ScanInfoRoundTrip.respond(to:)`, never hand-authored (threat
// T-08-02-02: a fabricated/empty log forging the round trip). It is a simple append-only recorder, OFF
// any hot path (the demo surfaces the last line in its UI; CI asserts one entry per cycle).
//
// `mach_absolute_time()`-derived timestamps are confined to this LOG (asserted monotonic, not exact);
// the INTENT computation in `ScanInfoRoundTrip` stays a pure function (threat T-08-02-03).

/// One instrumented entry in the closed-loop round-trip log: a single Scan-Info-in -> intent-out cycle.
///
/// `nonisolated`: a pure `Sendable` value record, freely usable across isolation boundaries despite the
/// package's default `MainActor` isolation (mirrors the report structs in `BCIHIDReports.swift`).
public nonisolated struct RoundTripEntry: Sendable, Equatable {
  /// Monotonic timestamp (nanoseconds, from `mach_absolute_time()`) at which the cycle was recorded.
  public let timestampNs: UInt64
  /// The scan-cycle `seed` from the Scan-Info OUTPUT report — ties a cycle to its response.
  public let seed: UInt8
  /// The `selectedItem` carried IN by the host's Scan-Info OUTPUT report.
  public let selectedItemIn: UInt8
  /// The `numberOfItems` (scan-list size) carried IN by the Scan-Info OUTPUT report.
  public let numberOfItems: UInt8
  /// The focus `itemIndex` returned OUT in the Item-Selection INPUT report.
  public let itemIndexOut: UInt8
  /// The cursor (x, y, z) delta returned OUT in the Pointer INPUT report.
  public let pointerDelta: SIMD3<Int8>
  /// The monotonic cycle counter (0-based) for this cycle.
  public let cycleIndex: UInt64

  public init(
    timestampNs: UInt64,
    seed: UInt8,
    selectedItemIn: UInt8,
    numberOfItems: UInt8,
    itemIndexOut: UInt8,
    pointerDelta: SIMD3<Int8>,
    cycleIndex: UInt64
  ) {
    self.timestampNs = timestampNs
    self.seed = seed
    self.selectedItemIn = selectedItemIn
    self.numberOfItems = numberOfItems
    self.itemIndexOut = itemIndexOut
    self.pointerDelta = pointerDelta
    self.cycleIndex = cycleIndex
  }

  /// A single human-readable instrumented line for this cycle — the SC#2 evidence / demo-UI rendering:
  /// `cycle=N seed=S in=item:X/N out=item:Y ptr=(dx,dy,dz) t=…ns`.
  public var formattedLine: String {
    "cycle=\(cycleIndex) seed=\(seed) in=item:\(selectedItemIn)/\(numberOfItems) "
      + "out=item:\(itemIndexOut) ptr=(\(pointerDelta.x),\(pointerDelta.y),\(pointerDelta.z)) "
      + "t=\(timestampNs)ns"
  }
}

/// The append-only instrumented round-trip log. NOT on a hot path: a plain reference-typed recorder the
/// demo (Plan 03) holds to surface the live cycle log, and the SC#2 evidence regenerates from.
///
/// A `final class` (reference semantics) so a single log instance is shared by the round trip and its
/// observers; the package's default `MainActor` isolation applies (the log is touched off the hot path).
public final class RoundTripLog {
  private var storage: [RoundTripEntry] = []

  public init() {}

  /// Append one instrumented cycle entry. Called exactly once per `respond(to:)` (threat T-08-02-02).
  public func record(_ entry: RoundTripEntry) {
    storage.append(entry)
  }

  /// All recorded cycle entries, in cycle order.
  public var entries: [RoundTripEntry] {
    storage
  }

  /// The most recent cycle's instrumented line, or an empty-log placeholder. The single human-readable
  /// line the demo UI shows + the SC#2 "instrumented log shows the round trip" evidence cites.
  public func formattedLastLine() -> String {
    guard let last = storage.last else {
      return "round-trip log empty (no cycles recorded)"
    }
    return last.formattedLine
  }
}
