// KalmanConstants.swift — steady-state ReFIT-Kalman matrices (REFIT-01, D-15).
//
// GENERATED by Decoder/scripts/fit_kalman_gain.py (D-15) — re-run to regenerate; do NOT hand-edit
// the numeric literals (a hand-edit breaking the structural invariants fails KalmanConstantsTests
// and CI — threat T-07-01-02).
//
// Provenance:
//   dt          = 0.02  (20 ms tick, CONTEXT D-01)
//   noise source = default   seed = 0
//   DEFAULT Q/R (held-out Indy data absent): white-noise-jerk sigma_jerk^2=1.0, R=diag(0.25) per axis. Re-run with
//   --data-dir pointing at downloaded Indy .mat to fit R from decoder residuals (07-RESEARCH 3.2).
//
// Observability resolution (07-RESEARCH §2.3): the 6-DOF state [px,py,vx,vy,ax,ay] with a
// velocity-only measurement is NOT observable — position is a pure integrator no measurement
// corrects. The steady-state gain K is therefore solved on the OBSERVABLE 4-DOF [vx,vy,ax,ay]
// sub-block and embedded into a 6x2 K with ZERO position rows (rows 0,1). Position is synced
// externally each tick (Wave-2, Swift side) to the integrator's clamped cursor position. The
// 6-DOF *state* is retained end-to-end; only the *gain derivation* used the observable block.
//
// Hot-path discipline: Foundation-free (uses `import simd` only, never the Obj-C runtime) — the
// per-tick filter op (Plan 02) is fixed-dim simd mat-vecs, zero allocation (hotpath-policy.sh,
// which forbids the Foundation/ObjectiveC imports on the hot path Plan 02 adds CortexReFIT to).
import simd

/// Committed steady-state ReFIT-Kalman matrices for the 6-DOF constant-acceleration model.
///
/// Layout choice (CONTEXT "implementer's discretion"): Swift `simd` has no `SIMD6`, so each 6-wide row
/// of A and H is stored as a `SIMD8<Float>` with the last 2 lanes zero-padded — the pad lanes
/// contribute nothing to an inlined `simd_dot`, so the Wave-2 predict/update step
/// (`x⁻ = A·x`; `x = x⁻ + K·(z − H·x⁻)`) stays a handful of fixed-size simd dot products with no
/// heap. Only the first 6 lanes of each A/H row are meaningful.
///
/// `nonisolated`: the constants are immutable `Sendable` compile-time data, so the hot-path
/// ``KalmanFilter`` (which is `nonisolated` — it runs on the decoder pthread, SC#3, NOT the
/// package-default `MainActor`) can load A/H/K synchronously with no isolation hop. Mirrors how
/// `IntentRotation` / `CursorVelocity` opt out of `.defaultIsolation(MainActor.self)`.
public nonisolated enum KalmanConstants {
  /// Filter tick in seconds (20 ms, CONTEXT D-01).
  public static let dt: Float = 0.02

  /// 6x6 constant-acceleration transition A on [px,py,vx,vy,ax,ay] (6 rows; SIMD8 with 2 zero-pad
  /// lanes — Swift has no SIMD6). Columns 0..5 are [px,py,vx,vy,ax,ay]; columns 6,7 are padding.
  public static let A: [SIMD8<Float>] = [
    SIMD8<Float>(1.0, 0.0, 0.02, 0.0, 0.0002, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 1.0, 0.0, 0.02, 0.0, 0.0002, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 1.0, 0.0, 0.02, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 1.0, 0.0, 0.02, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
  ]

  /// 2x6 velocity-only measurement H = [0 I 0] (selects (vx,vy); 2 rows; SIMD8, 2 zero-pad lanes).
  public static let H: [SIMD8<Float>] = [
    SIMD8<Float>(0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0)
  ]

  /// 6x2 steady-state Kalman gain K with ZERO position rows (rows 0,1); 6 rows of (kx,ky).
  public static let K: [SIMD2<Float>] = [
    SIMD2<Float>(0.0, 0.0),
    SIMD2<Float>(0.0, 0.0),
    SIMD2<Float>(0.0392099203499935, 0.0),
    SIMD2<Float>(0.0, 0.03920992034999153),
    SIMD2<Float>(0.039207960001001047, 0.0),
    SIMD2<Float>(0.0, 0.03920796000099885)
  ]

  /// 4x4 process-noise covariance Q on the observable [vx,vy,ax,ay] block (provenance; 4 rows).
  public static let Qobs: [SIMD4<Float>] = [
    SIMD4<Float>(4e-08, 0.0, 4.000000000000001e-06, 0.0),
    SIMD4<Float>(0.0, 4e-08, 0.0, 4.000000000000001e-06),
    SIMD4<Float>(4.000000000000001e-06, 0.0, 0.0004, 0.0),
    SIMD4<Float>(0.0, 4.000000000000001e-06, 0.0, 0.0004)
  ]

  /// 2x2 measurement-noise covariance R on (vx,vy) (provenance; 2 rows).
  public static let R: [SIMD2<Float>] = [
    SIMD2<Float>(0.25, 0.0),
    SIMD2<Float>(0.0, 0.25)
  ]
}
