// KalmanConstants.swift — steady-state ReFIT-Kalman matrices (REFIT-01, D-15).
//
// GENERATED by Decoder/scripts/fit_kalman_gain.py (D-15) — re-run to regenerate; do NOT hand-edit
// the numeric literals (a hand-edit breaking the structural invariants fails KalmanConstantsTests
// and CI — threat T-07-01-02).
//
// Provenance:
//   dt          = 0.02  (20 ms tick, CONTEXT D-01)
//   noise source = indy-heldout   seed = 0
//   session=indy_20160630_01 sha256=2ca8f6b7fcfc n_heldout=14600 lag_bins=1 lambda=0.1 side_mm=171.6820
//   grid_units_per_cm=0.05824724 sigma_jerk_sq=6048.884948 R=diag(0.15044900,0.08920892) R_offdiag=-0.03146268
//   rho_closed_loop=0.818794 resid_rms_grid_s=(0.387902,0.298670) encoder_sha=f95b257bf247
//   velocity_sha=9d542cb51d4a resid_mean_grid_s=(-0.005409,+0.000946) heldout_r2_pooled=+0.144602
//   readout=shipped_pooled_ridge side_mm_source=ndt1.replay_export.workspace_from_cursor+section-3a-cross-check
//   two gains: K SHIPS (fit from the noise source above); phase7BaselineK is FROZEN on the
//   documented default Q/R and is read by the SYNTHETIC regression fixture only (Phase-10 D-09).
//   grid normalisation: R and Q are fit in GRID-UNITS/s using grid_units_per_cm = 10.0 / side_mm
//   (10-PREREGISTRATION section 4, pre-registered before the fit ran). A residual fit in cm/s and
//   normalised afterwards differs by grid_units_per_cm^2, which is large.
//
// Observability resolution (07-RESEARCH §2.3): the 6-DOF state [px,py,vx,vy,ax,ay] with a
// velocity-only measurement is NOT observable — position is a pure integrator no measurement
// corrects. The steady-state gain K is therefore solved on the OBSERVABLE 4-DOF [vx,vy,ax,ay]
// sub-block and embedded into a 6x2 K with ZERO position rows (rows 0,1). Position is synced
// externally each tick (Wave-2, Swift side) to the integrator's clamped cursor position. The
// 6-DOF *state* is retained end-to-end; only the *gain derivation* used the observable block.
//
// Hot-path discipline: Foundation-free (uses `import simd` only, never the Obj-C runtime) — the
// per-tick filter op (Plan 02) is fixed-dim simd mat-vecs, zero allocation (hotpath-policy.sh,
// which forbids the Foundation/ObjectiveC imports on the hot path Plan 02 adds CortexReFIT to).
import simd

/// Committed steady-state ReFIT-Kalman matrices for the 6-DOF constant-acceleration model.
///
/// Layout choice (CONTEXT "implementer's discretion"): Swift `simd` has no `SIMD6`, so each 6-wide row
/// of A and H is stored as a `SIMD8<Float>` with the last 2 lanes zero-padded — the pad lanes
/// contribute nothing to an inlined `simd_dot`, so the Wave-2 predict/update step
/// (`x⁻ = A·x`; `x = x⁻ + K·(z − H·x⁻)`) stays a handful of fixed-size simd dot products with no
/// heap. Only the first 6 lanes of each A/H row are meaningful.
///
/// `nonisolated`: the constants are immutable `Sendable` compile-time data, so the hot-path
/// ``KalmanFilter`` (which is `nonisolated` — it runs on the decoder pthread, SC#3, NOT the
/// package-default `MainActor`) can load A/H/K synchronously with no isolation hop. Mirrors how
/// `IntentRotation` / `CursorVelocity` opt out of `.defaultIsolation(MainActor.self)`.
public nonisolated enum KalmanConstants {
  /// Filter tick in seconds (20 ms, CONTEXT D-01).
  public static let dt: Float = 0.02

  /// 6x6 constant-acceleration transition A on [px,py,vx,vy,ax,ay] (6 rows; SIMD8 with 2 zero-pad
  /// lanes — Swift has no SIMD6). Columns 0..5 are [px,py,vx,vy,ax,ay]; columns 6,7 are padding.
  public static let A: [SIMD8<Float>] = [
    SIMD8<Float>(1.0, 0.0, 0.02, 0.0, 0.0002, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 1.0, 0.0, 0.02, 0.0, 0.0002, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 1.0, 0.0, 0.02, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 1.0, 0.0, 0.02, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
  ]

  /// 2x6 velocity-only measurement H = [0 I 0] (selects (vx,vy); 2 rows; SIMD8, 2 zero-pad lanes).
  public static let H: [SIMD8<Float>] = [
    SIMD8<Float>(0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    SIMD8<Float>(0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0)
  ]

  /// 6x2 steady-state Kalman gain K with ZERO position rows (rows 0,1); 6 rows of (kx,ky).
  /// This is the SHIPPED gain — every runtime filter uses it.
  public static let K: [SIMD2<Float>] = [
    SIMD2<Float>(0.0, 0.0),
    SIMD2<Float>(0.0, 0.0),
    SIMD2<Float>(0.32957715936826487, 0.0),
    SIMD2<Float>(0.0, 0.365826239915465),
    SIMD2<Float>(3.283578568566595, 0.0),
    SIMD2<Float>(0.0, 4.147321059692328)
  ]

  /// The FROZEN Phase-7 baseline gain: the gain the documented DEFAULT Q/R produces
  /// (sigma_jerk^2 = 1.0, R = diag(0.25) in grid-units/s). It exists so the SYNTHETIC
  /// regression fixture (`CortexReFITBench --smoke` -> `refit_bps.json`) keeps guarding the FILTER
  /// CODE with the gain HELD FIXED, and is therefore immune to a real-data re-fit of `K`. Phase-10
  /// D-09 requires that fixture to stay byte-identical, because a red build on a real-data finding
  /// is pressure to tune. The SHIPPED gain is `K` above; this constant is used by the synthetic
  /// fixture ONLY.
  public static let phase7BaselineK: [SIMD2<Float>] = [
    SIMD2<Float>(0.0, 0.0),
    SIMD2<Float>(0.0, 0.0),
    SIMD2<Float>(0.0392099203499935, 0.0),
    SIMD2<Float>(0.0, 0.03920992034999153),
    SIMD2<Float>(0.039207960001001047, 0.0),
    SIMD2<Float>(0.0, 0.03920796000099885)
  ]

  /// 4x4 process-noise covariance Q on the observable [vx,vy,ax,ay] block (provenance; 4 rows).
  public static let Qobs: [SIMD4<Float>] = [
    SIMD4<Float>(0.0002419553979314815, 0.0, 0.024195539793148153, 0.0),
    SIMD4<Float>(0.0, 0.0002419553979314815, 0.0, 0.024195539793148153),
    SIMD4<Float>(0.024195539793148153, 0.0, 2.419553979314815, 0.0),
    SIMD4<Float>(0.0, 0.024195539793148153, 0.0, 2.419553979314815)
  ]

  /// 2x2 measurement-noise covariance R on (vx,vy) (provenance; 2 rows).
  public static let R: [SIMD2<Float>] = [
    SIMD2<Float>(0.15044899551772603, 0.0),
    SIMD2<Float>(0.0, 0.08920891758412207)
  ]
}
