#ifndef CORTEX_RING_H
#define CORTEX_RING_H

#pragma once

/* AUTO-GENERATED by cbindgen from Packages/CortexRing/rust. DO NOT EDIT. Regenerate via `cargo build` (build.rs) or Tools/scripts/build-rust.sh; CI drift-gates this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Number of neural channels per frame.
 *
 * MUST equal `CORTEX_CHANNEL_COUNT` in
 * `Packages/CortexCore/Sources/CortexCoreC/include/cortex_shm.h` (D-11). The value `96` is the
 * Phase-2 placeholder; the real O'Doherty Indy/Loco count is confirmed against Zenodo 3854034 in
 * Phase 4. The MECHANISM (the static assert below) is what is frozen here — not the number.
 */
#define CORTEX_CHANNEL_COUNT 96

/**
 * Opaque SPSC ring handle. The C side only ever holds a `*mut CortexSpsc`; the layout is private
 * to Rust (Plan 02 fills it with the real ring). `_private: [u8; 0]` is the cbindgen idiom for an
 * opaque type — it emits `typedef struct CortexSpsc CortexSpsc;` with no field exposure.
 */
typedef struct CortexSpsc {
  uint8_t _private[0];
} CortexSpsc;

/**
 * A single acquisition frame: a monotonic timestamp + sequence number + the raw f16 channel
 * payload (carried as raw IEEE-754 half bits in `u16`, hardware `Float16` on both sides —
 * Phase 2 D-10). `#[repr(C)]` so the layout matches the cbindgen C header byte-for-byte and the
 * Swift consumer sees an identical struct across the FFI.
 */
typedef struct CortexFrame {
  /**
   * `mach_absolute_time`-derived nanoseconds (Phase 2 D-12 `ts_ns`).
   */
  uint64_t ts_ns;
  /**
   * Monotonic sequence number (Phase 2 D-12 `seq`); the FIFO + 1M-stress test asserts it
   * increases by exactly one per frame with zero loss.
   */
  uint64_t seq;
  /**
   * Raw IEEE-754 half (f16) bits, one per channel (Phase 2 D-10 `[ubyte]`/f16 layout).
   */
  uint16_t channel_data[CORTEX_CHANNEL_COUNT];
} CortexFrame;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Spike-A smoke: a non-identity transform (`x XOR 0x5A5A5A5A`) so the Swift test proves a real
 * round-trip through the xcframework C ABI rather than a hard-coded Swift constant.
 */
uint32_t cortex_ping(uint32_t x);

/**
 * Allocate an SPSC ring of `capacity` slots (the real algorithm in Plan 02 requires a power of
 * two). STUB: allocates the placeholder backing and returns its raw pointer; returns null if the
 * allocation logic ever panics (threat T-03-01-02).
 */
struct CortexSpsc *cortex_spsc_create(uintptr_t capacity);

/**
 * Push one frame. Returns `false` when the ring is full. STUB: always returns `false` (the real
 * publish lands in Plan 02). Wrapped in `catch_unwind` because it dereferences caller-supplied
 * raw pointers (`AssertUnwindSafe` — raw pointers are not `UnwindSafe`, and on unwind we return
 * the safe `false` default without observing any broken invariant).
 */
bool cortex_spsc_push(struct CortexSpsc *r, const struct CortexFrame *f);

/**
 * Pop one frame into `out`. Returns `false` when the ring is empty. STUB: always returns `false`
 * (the real consume lands in Plan 02). Same `catch_unwind` rationale as `push`.
 */
bool cortex_spsc_pop(struct CortexSpsc *r, struct CortexFrame *out);

/**
 * Destroy a ring previously returned by `cortex_spsc_create`. Reconstructs the box and drops it.
 * Null-safe and unwind-safe: a null handle is a no-op, and a panic during drop is swallowed so it
 * never crosses the C frame (threat T-03-01-02).
 */
void cortex_spsc_destroy(struct CortexSpsc *r);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CORTEX_RING_H */
