#ifndef CORTEX_RING_H
#define CORTEX_RING_H

#pragma once

/* AUTO-GENERATED by cbindgen from Packages/CortexRing/rust. DO NOT EDIT. Regenerate via `cargo build` (build.rs) or Tools/scripts/build-rust.sh; CI drift-gates this file. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Number of neural channels per frame.
 *
 * MUST equal `CORTEX_CHANNEL_COUNT` in
 * `Packages/CortexCore/Sources/CortexCoreC/include/cortex_shm.h` (D-11). The value `96` is the
 * Phase-2 placeholder; the real O'Doherty Indy/Loco count is confirmed against Zenodo 3854034 in
 * Phase 4. The MECHANISM (the static assert below) is what is frozen here — not the number.
 */
#define CORTEX_CHANNEL_COUNT 96

/**
 * Opaque SPSC ring handle. The C side only ever holds a `*mut CortexSpsc`; the layout is private
 * to Rust. `_private: [u8; 0]` is the cbindgen idiom for an opaque type — it emits
 * `typedef struct CortexSpsc CortexSpsc;` with no field exposure, so the C/Swift ABI is unchanged
 * from Plan 01 even though the *real* backing ([`RingHandle`]) is now behind it.
 */
typedef struct CortexSpsc {
  uint8_t _private[0];
} CortexSpsc;

/**
 * A single acquisition frame: a monotonic timestamp + sequence number + the raw f16 channel
 * payload (carried as raw IEEE-754 half bits in `u16`, hardware `Float16` on both sides —
 * Phase 2 D-10). `#[repr(C)]` so the layout matches the cbindgen C header byte-for-byte and the
 * Swift consumer sees an identical struct across the FFI.
 */
typedef struct CortexFrame {
  /**
   * `mach_absolute_time`-derived nanoseconds (Phase 2 D-12 `ts_ns`).
   */
  uint64_t ts_ns;
  /**
   * Monotonic sequence number (Phase 2 D-12 `seq`); the FIFO + 1M-stress test asserts it
   * increases by exactly one per frame with zero loss.
   */
  uint64_t seq;
  /**
   * Raw IEEE-754 half (f16) bits, one per channel (Phase 2 D-10 `[ubyte]`/f16 layout).
   */
  uint16_t channel_data[CORTEX_CHANNEL_COUNT];
} CortexFrame;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Spike-A smoke: a non-identity transform (`x XOR 0x5A5A5A5A`) so the Swift test proves a real
 * round-trip through the xcframework C ABI rather than a hard-coded Swift constant. Unchanged from
 * Plan 01.
 */
uint32_t cortex_ping(uint32_t x);

/**
 * Allocate an SPSC ring of `capacity` slots and return an opaque handle, or null on failure.
 *
 * `capacity` MUST be a non-zero power of two (the ring's `mask = capacity - 1` wrap arithmetic
 * requires it — threat T-03-02-04, integer/capacity guard). A zero or non-power-of-two capacity
 * returns null rather than panicking. Returns null if allocation logic ever unwinds (T-03-02-05).
 */
struct CortexSpsc *cortex_spsc_create(uintptr_t capacity);

/**
 * Push one frame (copied by value from `*f`). Returns `false` when the ring is full, or when
 * `r`/`f` is null. MUST be called only from the caller's single producer thread (SPSC contract).
 *
 * `catch_unwind` + `AssertUnwindSafe`: raw pointers are not `UnwindSafe`, and on unwind we return
 * the safe `false` default without observing any broken invariant (T-03-02-05).
 */
bool cortex_spsc_push(struct CortexSpsc *r, const struct CortexFrame *f);

/**
 * Pop one frame into `*out`. Returns `false` when the ring is empty, or when `r`/`out` is null.
 * MUST be called only from the caller's single consumer thread (SPSC contract).
 */
bool cortex_spsc_pop(struct CortexSpsc *r, struct CortexFrame *out);

/**
 * Destroy a ring previously returned by `cortex_spsc_create`. Null-tolerant and unwind-safe.
 *
 * Reconstructs the `Box<RingHandle>` and drops it; dropping the handle drops both ends, dropping
 * the last `Arc<Spsc>`, whose `Drop` drains any still-live slots (no double-free / no
 * uninitialized-slot drop — threats T-03-02-01 / T-03-02-02). The caller MUST NOT use `r` after
 * this call (use-after-free — T-03-02-01).
 */
void cortex_spsc_destroy(struct CortexSpsc *r);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CORTEX_RING_H */
