// ScanInfoRoundTripTests — Phase 8 (SYS-03/04, SC#2): the bidirectional closed-loop round trip over
// the BCI HID Scan-Info channel (CONTEXT D-05, RESEARCH §0.2/§1.1).
//
// The host emits a Scan-Info OUTPUT report (RID 4, host->device) carrying UI state; Cortex returns
// intent as an Item-Selection INPUT report (RID 4) + a Pointer report (RID 3); an instrumented log
// records the full cycle. This is the "instrumented log shows the round trip" SC#2 artifact —
// produced deterministically and unit-testably (no external app, no granted entitlement, no device).
//
// Threats mitigated HERE (threat_model T-08-02-01/02/03):
//   - T-08-02-01 (Tampering/DoS): numberOfItems=0 / out-of-range selectedItem must NOT cause an
//     out-of-bounds focus index or crash (Test 5).
//   - T-08-02-02 (Spoofing/Repudiation): the log is GENERATED by respond(to:) — exactly one entry per
//     call, recording the seed + in/out items (Test 3) — so it cannot be a fabricated/empty proof.
//   - T-08-02-03 (Tampering): the intent is a PURE function of the Scan-Info input — no RNG, no
//     wall-clock — so the round trip is reproducible (Test 4); timestamps (mach_absolute_time) are
//     confined to the LOG and asserted monotonic, not exact.
//
// Test-naming convention mirrors the CI-passing BCIHIDReportTests / CortexReFIT suites:
//   `@Test("descriptive")` + a camelCase function name (SwiftLint identifier_name-clean).
import Testing

@testable import CortexBCIHID

@Suite("ScanInfoRoundTripTests")
struct ScanInfoRoundTripTests {
  /// A representative Scan-Info output report (the host->device closed-loop channel input).
  private func scanInfo(
    selectedItem: UInt8,
    numberOfItems: UInt8,
    seed: UInt8
  ) -> BCIOutputScanInfoReport {
    BCIOutputScanInfoReport(
      selectedItem: selectedItem,
      numberOfItems: numberOfItems,
      seed: seed,
      itemControlType: 0,
      uiScanningLatencyInt: 0,
      uiScanningLatencyFrac: 0
    )
  }

  // Test 1 — given a Scan-Info report with selectedItem=3, numberOfItems=900(->wraps to UInt8 so use a
  // representable count), seed=7, respond(to:) returns a non-nil intent whose Item-Selection itemIndex
  // is a valid focus index in 0..<numberOfItems (deterministic for the inputs). NOTE: numberOfItems is
  // a UInt8 on the wire (Apple reference), so "900" from the plan narrative is exercised as the
  // clamping path in Test 5 (count 0 degenerate) + here with a representable count; the focus index is
  // always clamped to 0..<max(1, numberOfItems).
  @Test("respond returns a valid in-range item selection for a normal scan-info report")
  func respondReturnsValidItemSelection() throws {
    let trip = ScanInfoRoundTrip()
    let response = trip.respond(to: scanInfo(selectedItem: 3, numberOfItems: 30, seed: 7))
    // The intent carries an Item-Selection report (RID 4, device->host).
    #expect(response.itemSelection.reportId == BCIReportID.itemSelectionOrScanInfo.rawValue)
    // The focus index is a valid index into the scan list.
    #expect(response.itemSelection.itemIndex < 30)
  }

  // Test 2 — the response also produces a Pointer report whose position deltas are Int8 in -127...127
  // (the cursor-intent half of SYS-04). (Int8 is structurally bounded to -128...127; we additionally
  // assert the harness never emits the -128 sentinel, keeping deltas in the documented -127...127.)
  @Test("respond produces a pointer report with deltas in -127...127")
  func respondProducesPointerInRange() {
    let trip = ScanInfoRoundTrip()
    let response = trip.respond(to: scanInfo(selectedItem: 12, numberOfItems: 30, seed: 42))
    #expect(response.pointer.reportId == BCIReportID.pointer.rawValue)
    let (dx, dy, dz) = response.pointer.position
    for delta in [dx, dy, dz] {
      #expect(delta >= -127)
      #expect(delta <= 127)
    }
  }

  // Test 3 — each respond(to:) call appends exactly one RoundTripLog entry; the entry records the scan
  // seed, the selectedItem in, the itemIndex out, and a monotonic ns timestamp; two consecutive entries
  // have non-decreasing timestamps.
  @Test("respond appends exactly one instrumented log entry per cycle, with monotonic timestamps")
  func respondAppendsOneLogEntryPerCycle() throws {
    let trip = ScanInfoRoundTrip()
    #expect(trip.log.entries.isEmpty)

    let first = trip.respond(to: scanInfo(selectedItem: 5, numberOfItems: 30, seed: 11))
    #expect(trip.log.entries.count == 1)
    let second = trip.respond(to: scanInfo(selectedItem: 9, numberOfItems: 30, seed: 12))
    #expect(trip.log.entries.count == 2)

    let e0 = trip.log.entries[0]
    let e1 = trip.log.entries[1]

    // The first entry records the first cycle's in/out + seed.
    #expect(e0.seed == 11)
    #expect(e0.selectedItemIn == 5)
    #expect(e0.numberOfItems == 30)
    #expect(e0.itemIndexOut == first.itemSelection.itemIndex)
    #expect(e0.cycleIndex == 0)

    // The second entry records the second cycle.
    #expect(e1.seed == 12)
    #expect(e1.selectedItemIn == 9)
    #expect(e1.itemIndexOut == second.itemSelection.itemIndex)
    #expect(e1.cycleIndex == 1)

    // Timestamps are monotonic (non-decreasing) — mach_absolute_time is monotonic.
    #expect(e1.timestampNs >= e0.timestampNs)

    // The log renders a single human-readable instrumented line for the demo UI / SC#2 evidence.
    let line = trip.log.formattedLastLine()
    #expect(line.contains("cycle=1"))
    #expect(line.contains("seed=12"))
    #expect(line.contains("in=item:9/30"))
    #expect(line.contains("out=item:\(second.itemSelection.itemIndex)"))
    #expect(line.contains("ptr="))
  }

  // Test 4 — the round trip is deterministic: the same Scan-Info input produces the same intent + the
  // same log fields (excluding the wall-time-independent timestamp, asserted monotonic not exact)
  // across two independent runs (no RNG).
  @Test("respond is deterministic: identical scan-info input yields identical intent across runs")
  func respondIsDeterministic() {
    let input = scanInfo(selectedItem: 17, numberOfItems: 30, seed: 200)

    let tripA = ScanInfoRoundTrip()
    let a = tripA.respond(to: input)

    let tripB = ScanInfoRoundTrip()
    let b = tripB.respond(to: input)

    // Intent is byte-identical across two fresh instances (pure function of the input).
    #expect(a.itemSelection == b.itemSelection)
    #expect(a.pointer == b.pointer)

    // The log fields (excluding the timestamp) match too.
    let ea = tripA.log.entries[0]
    let eb = tripB.log.entries[0]
    #expect(ea.seed == eb.seed)
    #expect(ea.selectedItemIn == eb.selectedItemIn)
    #expect(ea.numberOfItems == eb.numberOfItems)
    #expect(ea.itemIndexOut == eb.itemIndexOut)
    #expect(ea.pointerDelta == eb.pointerDelta)
    #expect(ea.cycleIndex == eb.cycleIndex)

    // A second call on the SAME instance with the SAME input reproduces the same intent (the intent is
    // a pure function of the Scan-Info input — the cycle counter advances but the intent does not drift).
    let a2 = tripA.respond(to: input)
    #expect(a2.itemSelection == a.itemSelection)
    #expect(a2.pointer == a.pointer)
  }

  // Test 5 — a Scan-Info report with numberOfItems=0 (degenerate) is handled without crash:
  // respond(to:) returns a safe no-selection intent (itemIndex 0, zero pointer delta) and logs the
  // cycle (threat T-08-02-01).
  @Test("respond handles numberOfItems=0 with a safe no-selection intent and still logs the cycle")
  func respondHandlesZeroItemsSafely() {
    let trip = ScanInfoRoundTrip()
    let response = trip.respond(to: scanInfo(selectedItem: 250, numberOfItems: 0, seed: 3))

    // Safe no-selection: itemIndex 0, zero pointer delta — no out-of-bounds, no crash.
    #expect(response.itemSelection.itemIndex == 0)
    #expect(response.pointer.position == (0, 0, 0))

    // The cycle is still recorded (the log proves the degenerate cycle ran).
    #expect(trip.log.entries.count == 1)
    let entry = trip.log.entries[0]
    #expect(entry.numberOfItems == 0)
    #expect(entry.itemIndexOut == 0)
    #expect(entry.pointerDelta == SIMD3<Int8>(0, 0, 0))
  }
}
