@testable import CortexBCIHID

// ScanInfoRoundTripTests — Phase 8 (SYS-03/04, SC#2): the bidirectional closed-loop round trip over
// the BCI HID Scan-Info channel (CONTEXT D-05, RESEARCH §0.2/§1.1).
//
// The host emits a Scan-Info OUTPUT report (RID 4, host->device) carrying UI state; Cortex returns
// intent as an Item-Selection INPUT report (RID 4) + a Pointer report (RID 3); an instrumented log
// records the full cycle. This is the "instrumented log shows the round trip" SC#2 artifact —
// produced deterministically and unit-testably (no external app, no granted entitlement, no device).
//
// Threats mitigated HERE (threat_model T-08-02-01/02/03):
//   - T-08-02-01 (Tampering/DoS): numberOfItems=0 / out-of-range selectedItem must NOT cause an
//     out-of-bounds focus index or crash (Test 5).
//   - T-08-02-02 (Spoofing/Repudiation): the log is GENERATED by respond(to:) — exactly one entry per
//     call, recording the seed + in/out items (Test 3) — so it cannot be a fabricated/empty proof.
//   - T-08-02-03 (Tampering): the intent is a PURE function of the Scan-Info input — no entropy source,
//     no wall-clock — so the round trip is reproducible (Test 4); timestamps (mach_absolute_time) are
//     confined to the LOG and asserted monotonic, not exact.
//
// Test-naming convention mirrors the CI-passing BCIHIDReportTests / DaemonRegistrationTests suites:
//   `@Test("descriptive")` + a camelCase function name (SwiftLint identifier_name-clean).
import Testing

/// `ScanInfoRoundTrip` + `RoundTripLog` are MainActor-isolated (the package default
/// .defaultIsolation(MainActor.self)); the suite adopts the same isolation to drive them synchronously
/// (mirrors the DaemonRegistrationTests / CortexReFIT KalmanConstantsTests precedent). The intent stays a
/// PURE function regardless of isolation — determinism is asserted by `respondIsDeterministic`.
@Suite("ScanInfoRoundTripTests")
@MainActor
struct ScanInfoRoundTripTests {
  /// A representative Scan-Info output report (the host->device closed-loop channel input).
  private func scanInfo(
    selectedItem: UInt8,
    numberOfItems: UInt8,
    seed: UInt8
  ) -> BCIOutputScanInfoReport {
    BCIOutputScanInfoReport(
      selectedItem: selectedItem,
      numberOfItems: numberOfItems,
      seed: seed,
      itemControlType: 0,
      uiScanningLatencyInt: 0,
      uiScanningLatencyFrac: 0
    )
  }

  // Test 1 — given a Scan-Info report (selectedItem=3, a representable numberOfItems, seed=7),
  // respond(to:) returns an intent whose Item-Selection itemIndex is a valid focus index in
  // 0..<numberOfItems (deterministic for the inputs). NOTE: numberOfItems is a UInt8 on the wire (Apple
  // reference), so the plan's "900" is exercised as the clamp path (Test 5 count=0) + here with a
  // representable count; the focus index is always clamped to 0..<max(1, numberOfItems).
  @Test
  func `respond returns a valid in-range item selection for a normal scan-info report`() {
    let trip = ScanInfoRoundTrip()
    let response = trip.respond(to: scanInfo(selectedItem: 3, numberOfItems: 30, seed: 7))
    // The intent carries an Item-Selection report (RID 4, device->host).
    #expect(response.itemSelection.reportId == BCIReportID.itemSelectionOrScanInfo.rawValue)
    // The focus index is a valid index into the scan list.
    #expect(response.itemSelection.itemIndex < 30)
  }

  /// Test 2 — the response also produces a Pointer report whose position deltas are Int8 in -127...127
  /// (the cursor-intent half of SYS-04). Int8 is structurally bounded to -128...127; we additionally
  /// assert the harness never emits the -128 sentinel, keeping deltas in the documented -127...127.
  @Test
  func `respond produces a pointer report with deltas in -127...127`() {
    let trip = ScanInfoRoundTrip()
    let response = trip.respond(to: scanInfo(selectedItem: 12, numberOfItems: 30, seed: 42))
    #expect(response.pointer.reportId == BCIReportID.pointer.rawValue)
    let position = response.pointer.position
    for delta in [position.0, position.1, position.2] {
      #expect(delta >= -127)
      #expect(delta <= 127)
    }
  }

  /// Test 3 — each respond(to:) call appends exactly one RoundTripLog entry; the entry records the scan
  /// seed, the selectedItem in, the itemIndex out, and a monotonic ns timestamp; two consecutive entries
  /// have non-decreasing timestamps.
  @Test
  func `respond appends exactly one instrumented log entry per cycle, with monotonic timestamps`() {
    let trip = ScanInfoRoundTrip()
    #expect(trip.log.entries.isEmpty)

    let first = trip.respond(to: scanInfo(selectedItem: 5, numberOfItems: 30, seed: 11))
    #expect(trip.log.entries.count == 1)
    let second = trip.respond(to: scanInfo(selectedItem: 9, numberOfItems: 30, seed: 12))
    #expect(trip.log.entries.count == 2)

    let firstEntry = trip.log.entries[0]
    let secondEntry = trip.log.entries[1]

    // The first entry records the first cycle's in/out + seed.
    #expect(firstEntry.seed == 11)
    #expect(firstEntry.selectedItemIn == 5)
    #expect(firstEntry.numberOfItems == 30)
    #expect(firstEntry.itemIndexOut == first.itemSelection.itemIndex)
    #expect(firstEntry.cycleIndex == 0)

    // The second entry records the second cycle.
    #expect(secondEntry.seed == 12)
    #expect(secondEntry.selectedItemIn == 9)
    #expect(secondEntry.itemIndexOut == second.itemSelection.itemIndex)
    #expect(secondEntry.cycleIndex == 1)

    // Timestamps are monotonic (non-decreasing) — mach_absolute_time is monotonic.
    #expect(secondEntry.timestampNs >= firstEntry.timestampNs)

    // The log renders a single human-readable instrumented line for the demo UI / SC#2 evidence.
    let line = trip.log.formattedLastLine()
    #expect(line.contains("cycle=1"))
    #expect(line.contains("seed=12"))
    #expect(line.contains("in=item:9/30"))
    #expect(line.contains("out=item:\(second.itemSelection.itemIndex)"))
    #expect(line.contains("ptr="))
  }

  /// Test 4 — the round trip is deterministic: the same Scan-Info input produces the same intent + the
  /// same log fields (excluding the wall-time-independent timestamp, asserted monotonic not exact)
  /// across two independent runs (no entropy source).
  @Test
  func `respond is deterministic: identical scan-info input yields identical intent across runs`() {
    let input = scanInfo(selectedItem: 17, numberOfItems: 30, seed: 200)

    let tripA = ScanInfoRoundTrip()
    let responseA = tripA.respond(to: input)

    let tripB = ScanInfoRoundTrip()
    let responseB = tripB.respond(to: input)

    // Intent is byte-identical across two fresh instances (pure function of the input).
    #expect(responseA.itemSelection == responseB.itemSelection)
    #expect(responseA.pointer == responseB.pointer)

    // The log fields (excluding the timestamp) match too.
    let entryA = tripA.log.entries[0]
    let entryB = tripB.log.entries[0]
    #expect(entryA.seed == entryB.seed)
    #expect(entryA.selectedItemIn == entryB.selectedItemIn)
    #expect(entryA.numberOfItems == entryB.numberOfItems)
    #expect(entryA.itemIndexOut == entryB.itemIndexOut)
    #expect(entryA.pointerDelta == entryB.pointerDelta)
    #expect(entryA.cycleIndex == entryB.cycleIndex)

    // A second call on the SAME instance with the SAME input reproduces the same intent (the intent is
    // a pure function of the Scan-Info input — the cycle counter advances but the intent does not drift).
    let responseA2 = tripA.respond(to: input)
    #expect(responseA2.itemSelection == responseA.itemSelection)
    #expect(responseA2.pointer == responseA.pointer)
  }

  // Test 5 — a Scan-Info report with numberOfItems=0 (degenerate) is handled without crash:
  // respond(to:) returns a safe no-selection intent (itemIndex 0, zero pointer delta) and logs the
  // cycle (threat T-08-02-01).
  @Test
  func `respond handles numberOfItems=0 with a safe no-selection intent and still logs the cycle`() {
    let trip = ScanInfoRoundTrip()
    let response = trip.respond(to: scanInfo(selectedItem: 250, numberOfItems: 0, seed: 3))

    // Safe no-selection: itemIndex 0, zero pointer delta — no out-of-bounds, no crash.
    #expect(response.itemSelection.itemIndex == 0)
    #expect(response.pointer.position == (0, 0, 0))

    // The cycle is still recorded (the log proves the degenerate cycle ran).
    #expect(trip.log.entries.count == 1)
    let entry = trip.log.entries[0]
    #expect(entry.numberOfItems == 0)
    #expect(entry.itemIndexOut == 0)
    #expect(entry.pointerDelta == SIMD3<Int8>(0, 0, 0))
  }
}
